# GENERATED by mcp-proxy generate-security-baseline — DO NOT EDIT
# Source: mcp-proxy/src/security_baseline/
from __future__ import annotations

import re

# Keep in sync via: cargo run --bin generate-security-baseline -- --apply
SENSITIVE_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("path_traversal", re.compile("\\.\\./\\.\\./")),
    ("path_traversal", re.compile("%2e%2e")),
    ("%2E%2E", re.compile("%2E%2E")),
    ("path_traversal", re.compile("%252e%252e")),
    ("%252E%252E", re.compile("%252E%252E")),
    ("ssh", re.compile("~/.ssh/.*")),
    ("ssh", re.compile("\\.ssh/")),
    ("aws", re.compile("~/.aws/.*")),
    ("aws", re.compile("\\.aws/credentials")),
    ("gnupg", re.compile("~/.gnupg/.*")),
    ("/etc/shadow", re.compile("/etc/shadow")),
    ("/etc/passwd", re.compile("/etc/passwd")),
    (".env", re.compile("\\.env(\\.|$)")),
    ("id_rsa", re.compile("id_rsa(\\.|$)")),
    ("id_ed25519", re.compile("id_ed25519(\\.|$)")),
    ("kube_config", re.compile("\\.kube/config")),
    (".netrc", re.compile("\\.netrc")),
    (".pgpass", re.compile("\\.pgpass")),
]
