//! Emit generated policy / hooks / dashboard artifacts from the canonical baseline.
//!
//! Artifacts under `mcp-proxy/generated/` are the checked-in golden outputs.
//! Live copies (repo policy YAML, dashboard defaults, Cursor hooks patterns,
//! installer seed) are updated by `generate-security-baseline --apply`.

use std::fs;
use std::path::{Path, PathBuf};

use crate::policy::PolicyConfig;

use super::{
    dangerous_network_patterns, dangerous_shell_patterns, filesystem_read_tool_names,
    filesystem_write_tool_names, mandatory_policy_config, network_tool_names,
    sensitive_path_patterns, shell_tool_names, BASELINE_RISK_THRESHOLD, BASELINE_VERSION,
    CANONICAL_REDACT_KEYS,
};

pub const GENERATED_HEADER_YAML: &str =
    "# GENERATED by mcp-proxy generate-security-baseline — DO NOT EDIT\n# Source: mcp-proxy/src/security_baseline/\n";

pub const GENERATED_HEADER_TS: &str =
    "/** GENERATED by mcp-proxy generate-security-baseline — DO NOT EDIT\n * Source: mcp-proxy/src/security_baseline/\n */\n";

pub const GENERATED_HEADER_PY: &str =
    "# GENERATED by mcp-proxy generate-security-baseline — DO NOT EDIT\n# Source: mcp-proxy/src/security_baseline/\n";

/// Bundle of generated text artifacts.
#[derive(Debug, Clone)]
pub struct GeneratedArtifacts {
    pub policy_yaml: String,
    pub policy_defaults_ts: String,
    pub hook_patterns_py: String,
    pub install_seed_yaml: String,
}

/// Format the compact default YAML (legacy-friendly, used by repo + installer).
pub fn format_baseline_yaml(config: &PolicyConfig) -> String {
    let _ = config;
    let sensitive = sensitive_path_patterns();
    let shell = dangerous_shell_patterns();
    let network = dangerous_network_patterns();

    let mut out = String::new();
    out.push_str(GENERATED_HEADER_YAML);
    out.push_str(&format!("version: \"{BASELINE_VERSION}\"\n"));
    out.push_str("global:\n");
    out.push_str("  redact_keys:\n");
    for key in CANONICAL_REDACT_KEYS {
        out.push_str(&format!("    - {key}\n"));
    }
    out.push_str(&format!("  risk_threshold: {BASELINE_RISK_THRESHOLD}\n"));
    out.push_str("  block_patterns: &sensitive_paths\n");
    for pat in &sensitive {
        out.push_str(&format!("    - {}\n", yaml_single_quoted(pat)));
    }
    out.push_str("tools:\n");

    for name in shell_tool_names() {
        out.push_str(&format!("  - name: {name}\n"));
        out.push_str("    action: Confirm\n");
        out.push_str("    block_patterns:\n");
        for pat in &shell {
            out.push_str(&format!("      - {}\n", yaml_single_quoted(pat)));
        }
    }
    for name in filesystem_read_tool_names() {
        out.push_str(&format!("  - name: {name}\n"));
        out.push_str("    action: Allow\n");
        out.push_str("    block_patterns: *sensitive_paths\n");
    }
    for name in filesystem_write_tool_names() {
        out.push_str(&format!("  - name: {name}\n"));
        out.push_str("    action: Confirm\n");
        out.push_str("    block_patterns: *sensitive_paths\n");
    }
    for name in network_tool_names() {
        out.push_str(&format!("  - name: {name}\n"));
        out.push_str("    action: Allow\n");
        out.push_str("    block_patterns:\n");
        for pat in &network {
            out.push_str(&format!("      - {}\n", yaml_single_quoted(pat)));
        }
    }
    out
}

fn yaml_single_quoted(s: &str) -> String {
    let escaped = s.replace('\'', "''");
    format!("'{escaped}'")
}

fn js_string_raw(s: &str) -> String {
    // Prefer String.raw`...` when no backticks; otherwise JSON-escape.
    if !s.contains('`') && !s.contains("${") {
        format!("String.raw`{s}`")
    } else {
        format!("{:?}", s)
    }
}

fn format_policy_defaults_ts(config: &PolicyConfig) -> String {
    let _ = config;
    let sensitive = sensitive_path_patterns();
    let shell = dangerous_shell_patterns();
    let network = dangerous_network_patterns();

    let mut out = String::new();
    out.push_str(GENERATED_HEADER_TS);
    out.push_str("import type { PolicyDocument } from \"./types\";\n\n");
    out.push_str("/** Default corporate policy aligned with the canonical security baseline. */\n");
    out.push_str("export const DEFAULT_POLICY: PolicyDocument = {\n");
    out.push_str(&format!("  version: \"{BASELINE_VERSION}\",\n"));
    out.push_str("  global: {\n");
    out.push_str("    redact_keys: [\n");
    for key in CANONICAL_REDACT_KEYS {
        out.push_str(&format!("      \"{key}\",\n"));
    }
    out.push_str("    ],\n");
    // Dashboard authoring default stays slightly stricter than runtime threshold.
    out.push_str(&format!("    risk_threshold: {BASELINE_RISK_THRESHOLD},\n"));
    out.push_str("  },\n");
    out.push_str("  tools: [\n");

    // Compact surface for the composer UI (primary tools).
    let primary_shell = ["execute_bash", "run_terminal_cmd"];
    for name in primary_shell {
        out.push_str("    {\n");
        out.push_str(&format!("      name: \"{name}\",\n"));
        out.push_str("      action: \"Confirm\",\n");
        out.push_str("      block_patterns: [\n");
        for pat in &shell {
            out.push_str(&format!("        {},\n", js_string_raw(pat)));
        }
        out.push_str("      ],\n");
        out.push_str("    },\n");
    }
    out.push_str("    {\n");
    out.push_str("      name: \"read_file\",\n");
    out.push_str("      action: \"Allow\",\n");
    out.push_str("      block_patterns: [\n");
    for pat in &sensitive {
        out.push_str(&format!("        {},\n", js_string_raw(pat)));
    }
    out.push_str("      ],\n");
    out.push_str("    },\n");
    out.push_str("    {\n");
    out.push_str("      name: \"write_file\",\n");
    out.push_str("      action: \"Confirm\",\n");
    out.push_str("      block_patterns: [\n");
    for pat in &sensitive {
        out.push_str(&format!("        {},\n", js_string_raw(pat)));
    }
    out.push_str("      ],\n");
    out.push_str("    },\n");
    out.push_str("    {\n");
    out.push_str("      name: \"fetch\",\n");
    out.push_str("      action: \"Allow\",\n");
    out.push_str("      block_patterns: [\n");
    for pat in &network {
        out.push_str(&format!("        {},\n", js_string_raw(pat)));
    }
    out.push_str("      ],\n");
    out.push_str("    },\n");
    out.push_str("  ],\n");
    out.push_str("};\n\n");
    out.push_str("export const MANAGED_TOOLS = [\n");
    out.push_str("  \"execute_bash\",\n");
    out.push_str("  \"run_terminal_cmd\",\n");
    out.push_str("  \"read_file\",\n");
    out.push_str("  \"write_file\",\n");
    out.push_str("  \"fetch\",\n");
    out.push_str("] as const;\n");
    out
}

fn format_hook_patterns_py() -> String {
    let sensitive = sensitive_path_patterns();
    let mut out = String::new();
    out.push_str(GENERATED_HEADER_PY);
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("import re\n\n");
    out.push_str("# Keep in sync via: cargo run --bin generate-security-baseline -- --apply\n");
    out.push_str("SENSITIVE_PATTERNS: list[tuple[str, re.Pattern[str]]] = [\n");
    for pat in &sensitive {
        let label = hook_label(pat);
        // Use non-raw Python string literals (Debug escapes) so `\.` stays correct.
        out.push_str(&format!(
            "    ({label:?}, re.compile({pat:?})),\n",
            label = label,
            pat = pat
        ));
    }
    out.push_str("]\n");
    out
}

fn hook_label(pat: &str) -> String {
    if pat.contains("ssh") {
        return "ssh".into();
    }
    if pat.contains("aws") {
        return "aws".into();
    }
    if pat.contains("gnupg") {
        return "gnupg".into();
    }
    if pat.contains("id_rsa") {
        return "id_rsa".into();
    }
    if pat.contains("id_ed25519") {
        return "id_ed25519".into();
    }
    if pat.contains(".env") {
        return ".env".into();
    }
    if pat.contains("2e") || pat.contains(r"\.\.") {
        return "path_traversal".into();
    }
    if pat.contains("shadow") {
        return "/etc/shadow".into();
    }
    if pat.contains("passwd") {
        return "/etc/passwd".into();
    }
    if pat.contains("kube") {
        return "kube_config".into();
    }
    if pat.contains("netrc") {
        return ".netrc".into();
    }
    if pat.contains("pgpass") {
        return ".pgpass".into();
    }
    pat.chars().take(32).collect()
}

/// Build all generated artifact strings from the canonical baseline.
pub fn generate_all() -> GeneratedArtifacts {
    let config = mandatory_policy_config();
    GeneratedArtifacts {
        policy_yaml: format_baseline_yaml(&config),
        policy_defaults_ts: format_policy_defaults_ts(&config),
        hook_patterns_py: format_hook_patterns_py(),
        install_seed_yaml: format_baseline_yaml(&config),
    }
}

fn repo_root_from_manifest_dir() -> PathBuf {
    // CARGO_MANIFEST_DIR = …/mcp-proxy
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Write golden files under `mcp-proxy/generated/` and optionally apply to live paths.
pub fn write_generated_tree(apply: bool) -> anyhow::Result<Vec<PathBuf>> {
    let root = repo_root_from_manifest_dir();
    let gen_dir = root.join("generated");
    fs::create_dir_all(&gen_dir)?;
    let arts = generate_all();
    let mut written = Vec::new();

    let pairs = [
        (gen_dir.join("mcp-policy.yaml"), arts.policy_yaml.as_str()),
        (
            gen_dir.join("policy-defaults.ts"),
            arts.policy_defaults_ts.as_str(),
        ),
        (
            gen_dir.join("hook_patterns.py"),
            arts.hook_patterns_py.as_str(),
        ),
        (
            gen_dir.join("install-policy-seed.yaml"),
            arts.install_seed_yaml.as_str(),
        ),
    ];
    for (path, content) in pairs {
        fs::write(&path, content)?;
        written.push(path);
    }

    if apply {
        written.extend(apply_to_live_paths(&root, &arts)?);
    }
    Ok(written)
}

fn apply_to_live_paths(
    mcp_proxy_root: &Path,
    arts: &GeneratedArtifacts,
) -> anyhow::Result<Vec<PathBuf>> {
    let repo = mcp_proxy_root
        .parent()
        .ok_or_else(|| anyhow::anyhow!("mcp-proxy parent missing"))?;
    let mut written = Vec::new();

    let policy = mcp_proxy_root.join("mcp-policy.yaml");
    fs::write(&policy, &arts.policy_yaml)?;
    written.push(policy);

    let dash = repo.join("mcp-dashboard/lib/policy-defaults.ts");
    if dash.parent().map(|p| p.exists()).unwrap_or(false) {
        fs::write(&dash, &arts.policy_defaults_ts)?;
        written.push(dash);
    }

    let hooks_gen = repo.join(".cursor/hooks/generated_sensitive_patterns.py");
    fs::create_dir_all(hooks_gen.parent().unwrap())?;
    fs::write(&hooks_gen, &arts.hook_patterns_py)?;
    written.push(hooks_gen);

    patch_install_seed(mcp_proxy_root.join("install.sh"), &arts.install_seed_yaml)?;
    written.push(mcp_proxy_root.join("install.sh"));

    let public = repo.join("frontend/public/install.sh");
    if public.exists() {
        fs::copy(mcp_proxy_root.join("install.sh"), &public)?;
        written.push(public);
    }

    Ok(written)
}

const INSTALL_BEGIN: &str = "# BEGIN SECURITY_BASELINE_SEED";
const INSTALL_END: &str = "# END SECURITY_BASELINE_SEED";

fn patch_install_seed(path: PathBuf, seed_yaml: &str) -> anyhow::Result<()> {
    let original = fs::read_to_string(&path)?;
    let body = seed_yaml
        .lines()
        .filter(|l| !l.starts_with("# GENERATED") && !l.starts_with("# Source:"))
        .collect::<Vec<_>>()
        .join("\n");

    if original.contains(INSTALL_BEGIN) && original.contains(INSTALL_END) {
        let before = original
            .split(INSTALL_BEGIN)
            .next()
            .ok_or_else(|| anyhow::anyhow!("split before"))?;
        let after = original
            .split(INSTALL_END)
            .nth(1)
            .ok_or_else(|| anyhow::anyhow!("split after"))?;
        let rebuilt = format!("{before}{INSTALL_BEGIN}\n{body}\n{INSTALL_END}{after}");
        fs::write(&path, rebuilt)?;
        return Ok(());
    }

    // First-time: replace the heredoc YAML between `<<'YAML'` and `YAML`.
    let start_marker = "tee \"$policy_file\" >/dev/null <<'YAML'";
    let end_marker = "YAML\n      success \"Created default policy";
    let Some(start_idx) = original.find(start_marker) else {
        anyhow::bail!("install.sh seed heredoc start not found");
    };
    let after_start = start_idx + start_marker.len();
    let Some(rel_end) = original[after_start..].find(end_marker) else {
        anyhow::bail!("install.sh seed heredoc end not found");
    };
    let end_idx = after_start + rel_end;
    let mut rebuilt = String::new();
    rebuilt.push_str(&original[..after_start]);
    rebuilt.push('\n');
    rebuilt.push_str(INSTALL_BEGIN);
    rebuilt.push('\n');
    rebuilt.push_str(&body);
    rebuilt.push('\n');
    rebuilt.push_str(INSTALL_END);
    rebuilt.push('\n');
    rebuilt.push_str(&original[end_idx..]);
    fs::write(&path, rebuilt)?;
    Ok(())
}

/// Compare generated content to checked-in golden files (returns Err on drift).
pub fn assert_generated_in_sync() -> anyhow::Result<()> {
    let root = repo_root_from_manifest_dir();
    let arts = generate_all();
    let checks = [
        ("generated/mcp-policy.yaml", arts.policy_yaml.as_str()),
        (
            "generated/policy-defaults.ts",
            arts.policy_defaults_ts.as_str(),
        ),
        ("generated/hook_patterns.py", arts.hook_patterns_py.as_str()),
        (
            "generated/install-policy-seed.yaml",
            arts.install_seed_yaml.as_str(),
        ),
    ];
    for (rel, expected) in checks {
        let path = root.join(rel);
        if !path.exists() {
            anyhow::bail!("missing generated artifact {rel}; run generate-security-baseline");
        }
        let actual = fs::read_to_string(&path)?;
        if actual != expected {
            anyhow::bail!(
                "drift in {rel}; run: cargo run --bin generate-security-baseline -- --apply"
            );
        }
    }

    // Live policy YAML must match generated (modulo optional apply).
    let live = root.join("mcp-policy.yaml");
    if live.exists() {
        let live_txt = fs::read_to_string(&live)?;
        if live_txt != arts.policy_yaml {
            anyhow::bail!("mcp-policy.yaml drifted from generated baseline");
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::PolicyAction;

    #[test]
    fn yaml_contains_shell_and_sensitive() {
        let y = format_baseline_yaml(&mandatory_policy_config());
        assert!(y.contains("execute_bash"));
        assert!(y.contains("run_terminal_cmd"));
        assert!(y.contains("OPENAI_API_KEY"));
        assert!(y.contains("ANTHROPIC_API_KEY"));
        assert!(y.contains("%2e%2e"));
    }

    #[test]
    fn actions_are_stricter_or_equal() {
        let cfg = mandatory_policy_config();
        let bash = cfg.tools.iter().find(|t| t.name == "execute_bash").unwrap();
        assert_eq!(bash.action, PolicyAction::Confirm);
    }
}
